import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, Video, FileText, BarChart2 } from 'lucide-react';

const HomePage = () => {
  return (
    <div className="bg-gray-100">
      {/* Hero Section */}
      <section className="bg-blue-600 text-white py-20">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center">
            <div className="md:w-1/2 mb-8 md:mb-0">
              <h1 className="text-4xl md:text-5xl font-bold mb-4">Transform Your Learning Experience with AI</h1>
              <p className="text-xl mb-8">SummarEase uses advanced AI to create summaries, quizzes, and notes from educational videos, helping you learn more efficiently.</p>
              <Link to="/auth" className="bg-white text-blue-600 px-6 py-3 rounded-full font-semibold text-lg hover:bg-blue-100 transition duration-300">
                Try for Free
              </Link>
            </div>
            <div className="md:w-1/2">
              <img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="AI-powered learning" className="rounded-lg shadow-xl" />
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">How SummarEase Works</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <FeatureCard
              icon={<Video className="w-12 h-12 text-blue-500" />}
              title="Upload Video"
              description="Simply upload your educational video to our platform."
            />
            <FeatureCard
              icon={<BookOpen className="w-12 h-12 text-blue-500" />}
              title="AI-Generated Summary"
              description="Our AI creates a concise summary of the video content."
            />
            <FeatureCard
              icon={<FileText className="w-12 h-12 text-blue-500" />}
              title="Interactive Quizzes"
              description="Test your knowledge with automatically generated quizzes."
            />
            <FeatureCard
              icon={<BarChart2 className="w-12 h-12 text-blue-500" />}
              title="Performance Analytics"
              description="Track your progress and identify areas for improvement."
            />
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="bg-gray-200 py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">What Our Users Say</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <TestimonialCard
              quote="SummarEase has revolutionized the way I study. The AI-generated summaries save me hours of note-taking!"
              author="Sarah J., Student"
            />
            <TestimonialCard
              quote="As an educator, I find the quizzes generated by SummarEase incredibly helpful for assessing my students' understanding."
              author="Dr. Michael L., Professor"
            />
            <TestimonialCard
              quote="The performance analytics have helped me identify my weak areas and focus my study efforts more effectively."
              author="Alex T., Lifelong Learner"
            />
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-blue-600 text-white py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Transform Your Learning?</h2>
          <p className="text-xl mb-8">Join thousands of students and educators who are already benefiting from SummarEase.</p>
          <Link to="/auth" className="bg-white text-blue-600 px-6 py-3 rounded-full font-semibold text-lg hover:bg-blue-100 transition duration-300">
            Get Started for Free
          </Link>
        </div>
      </section>
    </div>
  );
};

const FeatureCard = ({ icon, title, description }) => (
  <div className="bg-white p-6 rounded-lg shadow-md text-center">
    <div className="flex justify-center mb-4">{icon}</div>
    <h3 className="text-xl font-semibold mb-2">{title}</h3>
    <p className="text-gray-600">{description}</p>
  </div>
);

const TestimonialCard = ({ quote, author }) => (
  <div className="bg-white p-6 rounded-lg shadow-md">
    <p className="text-gray-600 mb-4">"{quote}"</p>
    <p className="font-semibold">- {author}</p>
  </div>
);

export default HomePage;