import React from 'react';

const Summary = ({ videoData }) => {
  // In a real application, you would fetch the summary from an AI service
  const summary = "This is a placeholder summary of the video content. In a real application, this would be generated by an AI service based on the video transcription.";

  return (
    <div>
      <h2 className="text-2xl font-bold mb-4">Video Summary</h2>
      {videoData ? (
        <div>
          <h3 className="text-xl font-semibold mb-2">{videoData.title}</h3>
          <p className="text-gray-600 mb-4">Duration: {videoData.duration}</p>
          <div className="bg-gray-100 p-4 rounded">
            <p>{summary}</p>
          </div>
        </div>
      ) : (
        <p>Please upload a video to generate a summary.</p>
      )}
    </div>
  );
};

export default Summary;